# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0002_auto_20170924_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mybitly_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.MyBitlyUrl')),
            ],
            options={
                'verbose_name_plural': 'Clicks count',
                'db_table': 'analytical_data',
                'verbose_name': 'Click count',
            },
        ),
    ]
