# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-24 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybitlyurl',
            name='active',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mybitlyurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
